SELECT * FROM all_objects WHERE object_name LIKE 'MTL%DEFAULT%';
DESC MTL_DEFAULT_CATEGORY_SETS
SELECT * FROM MTL_DEFAULT_CATEGORY_SETS;
SELECT * FROM all_views WHERE view_name = 'MTL_DEFAULT_SETS_VIEW';

SELECT S.CATEGORY_SET_ID ,
  ST.CATEGORY_SET_NAME ,
  ST.DESCRIPTION ,
  S.STRUCTURE_ID ,
  S.VALIDATE_FLAG ,
  D.FUNCTIONAL_AREA_ID
FROM MTL_CATEGORY_SETS_TL ST ,
  MTL_CATEGORY_SETS_B S ,
  MTL_DEFAULT_CATEGORY_SETS D
WHERE S.CATEGORY_SET_ID = ST.CATEGORY_SET_ID
AND ST.LANGUAGE         = userenv('LANG')
AND D.CATEGORY_SET_ID   = S.CATEGORY_SET_ID
/

select * FRom fnd_lookup_values where meaning like 'Inventory';
select * FRom fnd_lookup_values where lookup_type='MTL_FUNCTIONAL_AREAS';


desc MTL_DEFAULT_CATEGORY_SETS

